# vim:set ft=tmux:

# --> Oasis Bond (basically Twilight Dark)
set -ogq @thm_fg "#918ee8"
set -ogq @thm_primary "#5f5fd7"
set -ogq @thm_secondary "#8787ff"
set -ogq @thm_prefix "#34cb7d"

# Surfaces and overlays
set -ogq @thm_core "#2f2e50"
set -ogq @thm_mantle "#35345b"
set -ogq @thm_surface "#262541"

# General
set -ogq @thm_red "#d06666"
set -ogq @thm_orange "#ffa247"
set -ogq @thm_yellow "#f0e68c"
set -ogq @thm_darkyellow "#dec2ff"
set -ogq @thm_green "#34cb7d"
set -ogq @thm_teal "#8fd1c7"
set -ogq @thm_darkteal "#a8ddd5"
set -ogq @thm_blue "#519bff"
set -ogq @thm_indigo "#c28eff"
